import threading
import logging
from typing import Dict, Any, Optional, TYPE_CHECKING
from pydantic import BaseModel
from pylabcontrol_v2.core.base_instrument import BaseInstrument

if TYPE_CHECKING:
    from pylabcontrol_v2.core.base_mainframe import ChassisBase

class ModuleBase(BaseInstrument):
    """
    Proxy driver for dynamically discovered hardware modules.

    This class serves as a logical abstraction for sub-components installed within 
    a modular mainframe. It facilitates Nodal Injection by managing spatial 
    coordinates (slot, channel) and delegates all physical transport to the parent 
    chassis to maintain absolute thread safety across shared hardware buses.

    Attributes:
        slot (int): The physical hardware slot index this module occupies.
        _parent (ChassisBase): Reference to the parent multiplexer that owns the physical I/O.
        routing_kwargs (Dict[str, Any]): Dictionary of topological coordinates injected into SCPI templates.

    Engineering Context:
        Modules do not "own" a direct connection to the hardware adapter. In industrial-grade 
        control systems, multiple modules frequently share a single communication pipe (e.g., GPIB, USB). 
        Uncoordinated concurrent writes will lead to packet corruption and undefined hardware states. 
        This class mandates that every atomic I/O operation must acquire the parent's `io_lock`, 
        guaranteeing serialized, safe execution.
    """
    
    def __init__(self, parent_chassis: 'ChassisBase', slot_index: int, config: BaseModel) -> None:
        """
        Initializes the dynamic module proxy and establishes the routing context.

        Args:
            parent_chassis (ChassisBase): The mainframe handling physical I/O routing.
            slot_index (int): The integer slot identifier mapping to physical hardware.
            config (BaseModel): The dynamically loaded Pydantic TOML configuration schema.
        """
        self._parent = parent_chassis
        self.slot = slot_index
        # Inherit the shared hardware adapter from the chassis
        super().__init__(adapter=self._parent.adapter, config=config)
        
        # Inject our slot into the routing dictionary for descriptor templates
        self.routing_kwargs = {"slot": self.slot}

    def write_raw(self, command: str) -> None:
        """
        Transmits a raw SCPI string to the hardware via the parent's Mutex lock.

        Args:
            command (str): The fully formatted SCPI string ready for transport.
            
        Engineering Context:
            By overriding write_raw, we intercept the low-level traffic generated by 
            descriptors and ensure it passes through the chassis-level thread-safety 
            gatekeeper (`io_lock`).
        """
        with self._parent.io_lock:
            self.adapter.write(command)

    def query_raw(self, command: str) -> str:
        """
        Executes an atomic query operation via the parent's Mutex lock.

        Args:
            command (str): The SCPI query string.

        Returns:
            str: The raw hardware response string.
            
        Engineering Context:
            Serializes the "Write-then-Read" cycle, preventing other threads or 
            modules from injecting commands between the query and the response.
        """
        with self._parent.io_lock:
            return self.adapter.query(command)

class ChassisBase(BaseInstrument):
    """
    Physical I/O owner and topological multiplexer for multi-slot mainframes.

    The ChassisBase acts as the central orchestrator for modular hardware. It handles 
    the initial physical handshake, establishes the global synchronization lock, 
    and performs runtime discovery to dynamically hydrate its internal slot registry.

    Attributes:
        slots (Dict[int, ModuleBase]): Registry of discovered modules mapped by slot index.
        io_lock (threading.Lock): The global framework mutex ensuring atomic I/O.

    Engineering Context:
        Mainframes are treated as dynamic execution containers. By centralizing 
        concurrency control at the chassis level, the framework permits high-level 
        scripts to perform non-blocking, parallel operations (e.g., sweeping multiple 
        lasers simultaneously) while ensuring the underlying serial bus remains 
        uncorrupted by multiplexing collisions.
    """
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """
        Initializes the multiplexer and triggers topological discovery.

        Args:
            *args (Any): Positional arguments passed to BaseInstrument.
            **kwargs (Any): Keyword arguments passed to BaseInstrument.
        """
        super().__init__(*args, **kwargs)
        self.slots: Dict[int, ModuleBase] = {}
        self.io_lock = threading.Lock()
        
        # Trigger dynamic discovery upon instantiation if defined in the TOML
        if getattr(self.config, "is_mainframe", False) or "discovery_query" in self.config.scpi_commands:
            self.discover_modules()

    def discover_modules(self) -> None:
        """
        Interrogates physical slots to dynamically hydrate module proxies.

        This method executes a discovery loop across the hardware backplane, 
        identifying installed modules and mapping them to their corresponding 
        TOML configurations and explicit Python drivers.

        Engineering Context:
            Discovery is performed at runtime to ensure the software matches physical reality. 
            The engine utilizes Nodal Injection to query each slot's identification (`*IDN?`) 
            and employs the Factory to load the correct driver, prioritizing explicit 
            proxy classes defined in the TOML metadata.
        """
        from pylabcontrol_v2.utils.config_loader import ConfigLoader
        import importlib
        
        # Identify hardware bounds from metadata
        max_slots = getattr(self.config.metadata, "max_slots", 4)
        discovery_template = self.config.scpi_commands.get("discovery_query", "SLOT{slot}:IDN?")

        for slot_idx in range(max_slots + 1):  
            # Generate the nodal discovery query
            query = discovery_template.format(slot=slot_idx)
            
            with self.io_lock:
                try: 
                    # Interrogate slot; empty slots will throw or timeout
                    response = self.adapter.query(query).strip()
                except Exception: 
                    continue
                
            # Filter for valid hardware responses
            if response and "Empty" not in response and "ERROR" not in response:
                try:
                    # Parse standard Agilent/IEEE format: "Brand,Model,Serial,Firmware"
                    parts = response.split(',')
                    if len(parts) >= 2:
                        brand = parts[0].strip().lower()
                        model = parts[1].strip()
                        
                        # Fetch validated TOML config
                        module_config = ConfigLoader.load_config("modules", brand, model)
                        
                        # --- EXPLICIT PROXY RESOLUTION ---
                        # Allows for specialized logic (e.g. Laser vs Power Meter)
                        metadata = module_config.metadata or {}
                        if "driver_class" in metadata:
                            cat = metadata.get("driver_category", "modules")
                            file = metadata.get("driver_file", brand)
                            cls_name = metadata.get("driver_class")
                            
                            mod_path = f"pylabcontrol_v2.instruments.{cat}.{file}"
                            driver_mod = importlib.import_module(mod_path)
                            TargetClass = getattr(driver_mod, cls_name)
                            
                            # Bind specialized driver instance
                            self.slots[slot_idx] = TargetClass(self, slot_idx, module_config)
                        else:
                            # Bind generic ModuleBase proxy
                            self.slots[slot_idx] = ModuleBase(self, slot_idx, module_config)
                            
                        self.log.info(f"Discovered {brand.upper()} {model} in Slot {slot_idx}")
                except Exception as e:
                    self.log.error(f"Failed to load module in Slot {slot_idx}: {e}")